### PR TITLE
Exclude specs when measuring test coverage

### PR DESCRIPTION
**Pull request by mariosouto**
## Description

Test coverage should reveal which lines of code are we missing to test, it shouldn't measure that on the tests itself.

### CODE REVIEW

**Comment by santib** [comment]
@mariosouto Reading the documentation of simplecov, shouldn't we be using `SimpleCov.start 'rails'` instead? It automatically exclude test files (but it also count other files that are now being ignored)

**Comment by mariosouto** [comment]
@santib Agree, nice catch. I'll change to that

**Comment by santiagovidal** [comment]
Looks like you have to make some changes, because the total coverage went down. There's probably some folders that were ignored in the past, that aren't in the new configuration.

**Comment by jpascual1994** [comment]
@santib What about the total coverage? Is it correct?

**Comment by santib** [comment]
> @santib What about the total coverage? Is it correct?

I don't know, when I try to access that link I get a 500. I'm ok either fixing the coverage here or in a separate PR.

**Comment by juanmanuelramallo** [comment]
@mariosouto @andresg4 Any updates on this?

**Comment by mariosouto** [comment]
@juanmanuelramallo i have it on my pipeline, i'll resolve this by next week i hope

**Comment by mariosouto** [comment]
Sorry it took me so long to update this, i didn't use the following config

```rb
require 'simplecov'
SimpleCov.start 'rails'
```

Mainly because it doesn't count some folders that we typically use in our projects, for example `services/`, `queries/`, etc.

I added some tests as well.

Let me know your thoughts

**Pull request merged**
