### PR TITLE
Remove Facebook & Action Cable

### PR DESCRIPTION
**Pull request by MaicolBen**
This will be supported in https://github.com/rootstrap/rails_base

This should be squashed when merging with a better commit message

### CODE REVIEW

**Comment by santiagovidal** [comment]
We should update the readme.

**Comment by matiasmansilla1989** [comment]
@MaicolBen @fedeagripa @santiagovidal Should't we keep a facebook branch and maybe an Action Cable one? We should have some countermeasures in case something fails when we start using the new gem.

**Comment by MaicolBen** [comment]
@matiasmansilla1989 You can go back to this PR if you need Facebook. And if there is a bug in `rails-base` it should be fixed there, and if we cannot fix it there, we can always revert this PR in the future.

**Comment by matiasmansilla1989** [comment]
@MaicolBen Yes, you are right. I think most of the company know that we used to have facebook and it's obvious that you can go to previous PR.

**Comment by fedeagripa** [comment]
@santiagovidal readme updated

**Pull request merged**
